# Generated by Django 5.2.11 on 2026-02-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_events", "0016_alter_event_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationtransport",
            name="hyperlink_base_url",
            field=models.URLField(null=True),
        ),
    ]
