/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EventActionCategories } from "./EventActionCategories";
import {
    EventActionCategoriesFromJSON,
    EventActionCategoriesToJSON,
} from "./EventActionCategories";
import type { EventActions } from "./EventActions";
import { EventActionsFromJSON, EventActionsToJSON } from "./EventActions";

/**
 * A single selectable event action and the category it belongs to
 * @export
 * @interface EventActionChoice
 */
export interface EventActionChoice {
    /**
     *
     * @type {EventActions}
     * @memberof EventActionChoice
     */
    value: EventActions;
    /**
     *
     * @type {string}
     * @memberof EventActionChoice
     */
    label: string;
    /**
     *
     * @type {EventActionCategories}
     * @memberof EventActionChoice
     */
    category: EventActionCategories;
    /**
     *
     * @type {string}
     * @memberof EventActionChoice
     */
    categoryLabel: string;
}

/**
 * Check if a given object implements the EventActionChoice interface.
 */
export function instanceOfEventActionChoice(value: object): value is EventActionChoice {
    if (!("value" in value) || value["value"] === undefined) return false;
    if (!("label" in value) || value["label"] === undefined) return false;
    if (!("category" in value) || value["category"] === undefined) return false;
    if (
        (!("categoryLabel" in (value as Record<string, any>)) &&
            !("category_label" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["categoryLabel"] === undefined &&
            (value as Record<string, any>)["category_label"] === undefined)
    )
        return false;
    return true;
}

export function EventActionChoiceFromJSON(json: any): EventActionChoice {
    return EventActionChoiceFromJSONTyped(json, false);
}

export function EventActionChoiceFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): EventActionChoice {
    if (json == null) {
        return json;
    }
    return {
        value: EventActionsFromJSON(json["value"]),
        label: json["label"],
        category: EventActionCategoriesFromJSON(json["category"]),
        categoryLabel: json["category_label"],
    };
}

export function EventActionChoiceToJSON(json: any): EventActionChoice {
    return EventActionChoiceToJSONTyped(json, false);
}

export function EventActionChoiceToJSONTyped(
    value?: EventActionChoice | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        value: EventActionsToJSON(value["value"]),
        label: value["label"],
        category: EventActionCategoriesToJSON(value["category"]),
        category_label: value["categoryLabel"],
    };
}
