/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const EventActionCategories = {
    Authentication: "authentication",
    User: "user",
    Security: "security",
    Flows: "flows",
    System: "system",
    Data: "data",
    Governance: "governance",
    Custom: "custom",
    UnknownDefaultOpenApi: "11184809",
} as const;
export type EventActionCategories =
    (typeof EventActionCategories)[keyof typeof EventActionCategories];

export function instanceOfEventActionCategories(value: any): boolean {
    for (const key in EventActionCategories) {
        if (Object.prototype.hasOwnProperty.call(EventActionCategories, key)) {
            if (EventActionCategories[key as keyof typeof EventActionCategories] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EventActionCategoriesFromJSON(json: any): EventActionCategories {
    return EventActionCategoriesFromJSONTyped(json, false);
}

export function EventActionCategoriesFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): EventActionCategories {
    return json as EventActionCategories;
}

export function EventActionCategoriesToJSON(value?: EventActionCategories | null): any {
    return value as any;
}

export function EventActionCategoriesToJSONTyped(
    value: any,
    ignoreDiscriminator: boolean,
): EventActionCategories {
    return value as EventActionCategories;
}
